SELECT 
    V.CHAPA,
    F.NOME,
    V.CODEVENTO,
    E.DESCRICAO AS DESCRICAO_EVENTO,
    V.VALOR
FROM PFVALORFORCADO V
INNER JOIN PFUNC F 
    ON V.CODCOLIGADA = F.CODCOLIGADA 
    AND V.CHAPA = F.CHAPA
INNER JOIN PEVENTO E
    ON V.CODCOLIGADA = E.CODCOLIGADA
    AND V.CODEVENTO = E.CODIGO
WHERE V.CODCOLIGADA = 1
  AND V.NROPERIODO = 1
  AND V.MESCOMP = 6
  AND V.ANOCOMP = 2026
  AND F.CODSITUACAO = 'A';
