DECLARE @CODCOLIGADA INT = :$CODCOLIGADA
DECLARE @DTINICIO DATETIME = :PLN_$B$1_D
DECLARE @DTFIM DATETIME = :PLN_$B$2_D
DECLARE @CRITICA VARCHAR(1) = :PLN_$B$3_S;

WITH cte_HISTHOR AS
	(
	SELECT
		PFHSTHOR.CODCOLIGADA,
		PFHSTHOR.CHAPA,
		PFHSTHOR.DTMUDANCA,
		PFHSTHOR.CODHORARIO,
		'H' TIPO
	FROM PFHSTHOR
	WHERE
		PFHSTHOR.CODCOLIGADA = @CODCOLIGADA AND
		PFHSTHOR.DTMUDANCA <= @DTFIM
		
	UNION ALL
	
	SELECT
		AJORNADAFUN.CODCOLIGADA,
		AJORNADAFUN.CHAPA,
		AJORNADAFUN.DATAMUDANCA DTMUDANCA,
		AJORNADAFUN.CODHORARIO,
		'J' TIPO
	FROM AJORNADAFUN
	WHERE
		AJORNADAFUN.CODCOLIGADA = @CODCOLIGADA AND
		AJORNADAFUN.DATAMUDANCA <= @DTFIM
	),
	cte_BATIDAS AS
	(
	SELECT
		T.CODCOLIGADA,
		T.CHAPA,
		T.DATAREFERENCIA,
		T.BATIDA
	FROM
	(
	SELECT
		ABATFUN.CODCOLIGADA,
		ABATFUN.CHAPA,
		ABATFUN.DATAREFERENCIA,
		ABATFUN.BATIDA,
		ROW_NUMBER() OVER(PARTITION BY ABATFUN.CODCOLIGADA, ABATFUN.CHAPA, ABATFUN.DATAREFERENCIA ORDER BY ABATFUN.DATA, ABATFUN.BATIDA) SEQ
	FROM ABATFUN
	WHERE
		ABATFUN.CODCOLIGADA = @CODCOLIGADA
	) T
	WHERE
		SEQ = 1
	),

	cte_HORARIO AS
	(
	SELECT
		AHORARIO.CODCOLIGADA,
		AHORARIO.CODIGO AS CODHORARIO,
		AHORARIO.DESCRICAO AS HORARIO,
		(SELECT TOP 1
			AJORHOR.BATINICIO
		FROM AJORHOR
		WHERE
			AJORHOR.CODCOLIGADA = AHORARIO.CODCOLIGADA AND
			AJORHOR.CODHORARIO = AHORARIO.CODIGO 
		ORDER BY
			AJORHOR.INDINICIO,
			AJORHOR.BATINICIO
		) HORINICIO,
		'H' TIPO
	FROM AHORARIO
	WHERE
		AHORARIO.CODCOLIGADA = @CODCOLIGADA
		
	UNION ALL
	
	SELECT
		AHORARIOJORNADA.CODCOLIGADA,
		AHORARIOJORNADA.CODHORARIO,
		AHORARIOJORNADA.DESCRICAO AS HORARIO,
		'' HORAINICIO,
		'J' TIPO
	FROM AHORARIOJORNADA
	WHERE
		AHORARIOJORNADA.CODCOLIGADA = @CODCOLIGADA
	),
		
	cte_PERIODO AS
	(
	SELECT
		AAFHTFUN.CODCOLIGADA,
		AAFHTFUN.CHAPA,
		AAFHTFUN.DATA,
		CASE
			WHEN DATEPART(dw, AAFHTFUN.DATA) = 1 THEN 'DOM'
			WHEN DATEPART(dw, AAFHTFUN.DATA) = 2 THEN 'SEG'
			WHEN DATEPART(dw, AAFHTFUN.DATA) = 3 THEN 'TER'
			WHEN DATEPART(dw, AAFHTFUN.DATA) = 4 THEN 'QUA'
			WHEN DATEPART(dw, AAFHTFUN.DATA) = 5 THEN 'QUI'
			WHEN DATEPART(dw, AAFHTFUN.DATA) = 6 THEN 'SEX'
			WHEN DATEPART(dw, AAFHTFUN.DATA) = 7 THEN 'SAB'
		END DIA,
		CASE 
			WHEN AAFHTFUN.FERIADO > 0 THEN 'Feriado'
			WHEN AAFHTFUN.COMPENSADO > 0 THEN 'Compensado'
			WHEN AAFHTFUN.DESCANSO > 0 THEN 'Descanso'
			ELSE 'Normal'
		END TIPO,
		AAFHTFUN.BASE,
		AAFHTFUN.HTRAB,
		AAFHTFUN.EXTRAAUTORIZADO,
		AAFHTFUN.ATRASO,
		AAFHTFUN.FALTA,
		AAFHTFUN.ADICIONAL,
		(SELECT TOP 1
			DATEDIFF(mi, AOCORRENCIACALCULADA.INICIO,AOCORRENCIACALCULADA.FIM)+ISNULL(DATEDIFF(mi, AUX.INICIO,AUX.FIM),0)
		FROM AOCORRENCIACALCULADA(nolock)
		LEFT JOIN AOCORRENCIACALCULADA AUX(nolock) ON
			AUX.CODCOLIGADA = AOCORRENCIACALCULADA.CODCOLIGADA AND
			AUX.CHAPA = AOCORRENCIACALCULADA.CHAPA AND
			AUX.DATAREFERENCIA = AOCORRENCIACALCULADA.DATAREFERENCIA AND
			AUX.FIM = AOCORRENCIACALCULADA.INICIO AND
			AUX.TIPOOCORRENCIA IN ('EA')
		WHERE
			AOCORRENCIACALCULADA.CODCOLIGADA = AAFHTFUN.CODCOLIGADA AND
			AOCORRENCIACALCULADA.CHAPA = AAFHTFUN.CHAPA AND
			AOCORRENCIACALCULADA.DATAREFERENCIA = AAFHTFUN.DATA AND
			AOCORRENCIACALCULADA.TIPOOCORRENCIA = 'T'
		ORDER BY
			AOCORRENCIACALCULADA.INICIO
		) TRABINICIO,
		ISNULL(
		(SELECT
			SUM(DATEDIFF(mi, AOCORRENCIACALCULADA.INICIO,AOCORRENCIACALCULADA.FIM))
		FROM AOCORRENCIACALCULADA(nolock)
		WHERE
			AOCORRENCIACALCULADA.CODCOLIGADA = AAFHTFUN.CODCOLIGADA AND
			AOCORRENCIACALCULADA.CHAPA = AAFHTFUN.CHAPA AND
			AOCORRENCIACALCULADA.DATAREFERENCIA = AAFHTFUN.DATA AND
			AOCORRENCIACALCULADA.TIPOOCORRENCIA = 'AREF' AND
			(
			EXISTS (SELECT 1
					FROM ABATFUN
					WHERE
						ABATFUN.CODCOLIGADA = AAFHTFUN.CODCOLIGADA AND
						ABATFUN.CHAPA = AAFHTFUN.CHAPA AND
						ISNULL(ABATFUN.DATAREFERENCIA,ABATFUN.BATIDA) = AOCORRENCIACALCULADA.DATAREFERENCIA AND
						ABATFUN.BATIDA = (DATEPART(HH,AOCORRENCIACALCULADA.INICIO)*60)+DATEPART(mi,AOCORRENCIACALCULADA.INICIO)
						) AND
			EXISTS (SELECT 1
					FROM ABATFUN
					WHERE
						ABATFUN.CODCOLIGADA = AAFHTFUN.CODCOLIGADA AND
						ABATFUN.CHAPA = AAFHTFUN.CHAPA AND
						ISNULL(ABATFUN.DATAREFERENCIA,ABATFUN.BATIDA) = AOCORRENCIACALCULADA.DATAREFERENCIA AND
						ABATFUN.BATIDA >= (DATEPART(HH,AOCORRENCIACALCULADA.FIM)*60)+DATEPART(mi,AOCORRENCIACALCULADA.FIM)
					)
				)
			),
			(SELECT
				MAX(CASE WHEN SEQ = 3 THEN BATIDA ELSE 0 END) -
				MAX(CASE WHEN SEQ = 2 THEN BATIDA ELSE 0 END)
			FROM
			(SELECT
				ABATFUN.DATAREFERENCIA,
				ABATFUN.BATIDA,
				ROW_NUMBER() OVER(ORDER BY ISNULL(ABATFUN.DATAREFERENCIA,ABATFUN.DATA), ABATFUN.BATIDA) SEQ
			FROM ABATFUN
			WHERE
				ABATFUN.CODCOLIGADA = AAFHTFUN.CODCOLIGADA AND
				ABATFUN.CHAPA = AAFHTFUN.CHAPA AND
				ISNULL(ABATFUN.DATAREFERENCIA,ABATFUN.DATA) = AAFHTFUN.DATA
			) T
			WHERE
				SEQ IN (2,3)
			HAVING
				(MAX(CASE WHEN SEQ = 3 THEN BATIDA ELSE 0 END) -
				MAX(CASE WHEN SEQ = 2 THEN BATIDA ELSE 0 END)) > 0
			)
			) AS REF,
			ISNULL(
			(SELECT TOP 1
				0
			FROM AAFHTFUN AS AUX
			WHERE
				AUX.CODCOLIGADA = AAFHTFUN.CODCOLIGADA AND
				AUX.CHAPA = AAFHTFUN.CHAPA AND
				AUX.DATA BETWEEN DATEADD(DAY, -6, AAFHTFUN.DATA) AND AAFHTFUN.DATA AND
				AUX.HTRAB = 0
			),1) AS FOLGA7DIAS,
			CASE 
				WHEN AAFHTFUN.DATA = EOMONTH(AAFHTFUN.DATA) THEN
					ISNULL(
					(SELECT TOP 1
						0
					FROM AAFHTFUN AS AUX
					WHERE
						AUX.CODCOLIGADA = AAFHTFUN.CODCOLIGADA AND
						AUX.CHAPA = AAFHTFUN.CHAPA AND
						MONTH(AUX.DATA) = MONTH(AAFHTFUN.DATA) AND
						YEAR(AUX.DATA) = YEAR(AAFHTFUN.DATA) AND
						DATEPART(dw, AUX.DATA) = 1 AND
						AUX.HTRAB = 0 
					),1)
			END AS FOLGADOMINGO
		
	FROM AAFHTFUN
	WHERE
		AAFHTFUN.CODCOLIGADA = @CODCOLIGADA AND
		AAFHTFUN.DATA BETWEEN @DTINICIO AND @DTFIM
	),
	cte_CRITICAS AS
	(
	SELECT
		T.CODCOLIGADA,
		T.CHAPA,
		T.DATA,
		MAX(T.CRITICAINTERJORNADA) AS CRITICAINTERJORNADA,
		MAX(T.CRITICAMAIS10H) AS CRITICAMAIS10H,
		MAX(T.CRITICABATSEMPAR) AS CRITICABATSEMPAR
	FROM
	(
	SELECT
		AAVISOCALCULADO.CODCOLIGADA,
		AAVISOCALCULADO.CHAPA,
		AAVISOCALCULADO.DATAREFERENCIA AS DATA,
		CASE WHEN AAVISOCALCULADO.CODAVISO = 1 THEN 1 ELSE 0 END AS CRITICAINTERJORNADA,
		CASE WHEN AAVISOCALCULADO.CODAVISO = 2 THEN 1 ELSE 0 END AS CRITICAMAIS10H,
		CASE WHEN AAVISOCALCULADO.CODAVISO = 5 THEN 1 ELSE 0 END AS CRITICABATSEMPAR
	
	FROM AAVISOCALCULADO
	WHERE
		AAVISOCALCULADO.CODCOLIGADA = @CODCOLIGADA AND
		AAVISOCALCULADO.DATAREFERENCIA BETWEEN @DTINICIO AND @DTFIM AND
		AAVISOCALCULADO.CODAVISO IN (1,2,5)
		
  

	) T
	GROUP BY
		T.CODCOLIGADA,
		T.CHAPA,
		T.DATA
	),
	
	cte_BANCO AS
	(
	SELECT
		ABANCOHORFUN.CODCOLIGADA,
		ABANCOHORFUN.CHAPA,
		ABANCOHORFUN.DATA,
		SUM(ABANCOHORFUN.EXTRAFAIXA1+ABANCOHORFUN.EXTRAFAIXA2+ABANCOHORFUN.EXTRAFAIXA3+ABANCOHORFUN.EXTRAFAIXA4+ABANCOHORFUN.EXTRAFAIXA5+ABANCOHORFUN.EXTRADESC1+ABANCOHORFUN.EXTRADESC2+ABANCOHORFUN.EXTRAFER1+ABANCOHORFUN.EXTRAFER2+ABANCOHORFUN.EXTRACOMP1+ABANCOHORFUN.EXTRACOMP2)-SUM(ABANCOHORFUN.FALTA+ABANCOHORFUN.ATRASO) AS HORAS
	FROM ABANCOHORFUN
	WHERE
		ABANCOHORFUN.CODCOLIGADA = @CODCOLIGADA AND
		ABANCOHORFUN.DATA BETWEEN @DTINICIO AND @DTFIM
	GROUP BY
		ABANCOHORFUN.CODCOLIGADA,
		ABANCOHORFUN.CHAPA,
		ABANCOHORFUN.DATA
	),
	cte_EXTRAS AS
	(
	SELECT
		AMOVFUNDIA.CODCOLIGADA,
		AMOVFUNDIA.CHAPA,
		AMOVFUNDIA.DATA,
		SUM(AMOVFUNDIA.NUMHORAS) AS HORAS
	FROM AMOVFUNDIA
	JOIN PEVENTO ON
		PEVENTO.CODCOLIGADA = AMOVFUNDIA.CODCOLIGADA AND
		PEVENTO.CODIGO = AMOVFUNDIA.CODEVE AND
		PEVENTO.PORCINCID > 1 AND
		PEVENTO.VALHORDIAREF = 'H' 
	WHERE
		AMOVFUNDIA.CODCOLIGADA = @CODCOLIGADA AND
		AMOVFUNDIA.DATA BETWEEN @DTINICIO AND @DTFIM
	GROUP BY
		AMOVFUNDIA.CODCOLIGADA,
		AMOVFUNDIA.CHAPA,
		AMOVFUNDIA.DATA
		
	),
	
	cte_FUNC AS
	(
	SELECT
		PFUNC.CODCOLIGADA,
		PFUNC.CHAPA,
		PFUNC.NOME,
		PFUNC.DATAADMISSAO,
		PFUNC.DTTRANSFERENCIA,
		PFUNC.CODTIPO,
		PFUNC.CODSECAO,
		PSECAO.DESCRICAO SECAO,
		isnull(
		(SELECT TOP 1
			AUX.NOME
		FROM PSUBSTSUP
		JOIN PFUNC AUX ON
			AUX.CODCOLIGADA = PSUBSTSUP.CODCOLIGADA AND
			AUX.CHAPA = PSUBSTSUP.CHAPASUBST
		WHERE
			PSUBSTSUP.CODCOLIGADA = PFUNC.CODCOLIGADA AND
			PSUBSTSUP.CODSECAO = PFUNC.CODSECAO AND
			PSUBSTSUP.CODEQUIPE = PFUNC.CODEQUIPE AND
			PSUBSTSUP.CHAPASUBST <> PFUNC.CHAPA AND
			PSUBSTSUP.DATAINICIO <= CONVERT(DATE, GETDATE()) AND
			PSUBSTSUP.DATAFIM IS NULL
		),
		(SELECT TOP 1
			AUX.NOME
		FROM PSUBSTCHEFE
		JOIN PFUNC AUX ON
			AUX.CODCOLIGADA = PSUBSTCHEFE.CODCOLSUBST AND
			AUX.CHAPA = PSUBSTCHEFE.CHAPASUBST
		WHERE
			PSUBSTCHEFE.CODCOLIGADA = PFUNC.CODCOLIGADA AND
			PSUBSTCHEFE.CODSECAO = SUBSTRING(PFUNC.CODSECAO, 1, LEN(PSUBSTCHEFE.CODSECAO)) AND
			PSUBSTCHEFE.CHAPASUBST <> PFUNC.CHAPA AND
			PSUBSTCHEFE.DATAINICIO <= CONVERT(DATE, GETDATE()) AND
			PSUBSTCHEFE.DATAFIM IS NULL
		ORDER BY
			LEN(PSUBSTCHEFE.CODSECAO) DESC,
			PSUBSTCHEFE.DATAINICIO
		)) CHEFEDIRETO
	
	FROM PFUNC
	JOIN PSECAO ON
		PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA AND
		PSECAO.CODIGO = PFUNC.CODSECAO
	WHERE
		PFUNC.CODCOLIGADA = @CODCOLIGADA AND
		PFUNC.DATAADMISSAO <= @DTFIM AND
		(PFUNC.DATADEMISSAO IS NULL OR PFUNC.DATADEMISSAO >= @DTINICIO)
	)

SELECT
	CODCOLIGADA 'Col',
	CHAPA 'Chapa',
	NOME 'Nome',
	DATAADMISSAO 'Dt AdmissÃ£o',
	DATA 'Data',
	DIA 'Dia Sem',
	TIPO 'Tipo Dia',
	HORARIO 'Horario',
	CODHORARIO 'CÃ³d Horario',
	CRITICAREF 'RefeiÃ§Ã£o',
	CASE WHEN CRITICAINTERJORNADA = 1 THEN 'Sim' ELSE 'NÃ£o' END 'Interjornada',
	CASE WHEN CRITICABATSEMPAR = 1 THEN 'Sim' ELSE 'NÃ£o' END 'Batida sem par',
	CASE WHEN CRITICAPAUSA = 1 THEN 'Sim' ELSE 'NÃ£o' END 'Pausa > 6h',
	CASE WHEN CRITICAMAIS10H = 1 THEN 'Sim' ELSE 'NÃ£o' END 'Trabalho > 10h',
	CASE WHEN FOLGA7DIAS = 1 THEN 'Sim' ELSE 'NÃ£o' END 'Sem Folga 7 dias',
	CASE WHEN FOLGADOMINGO = 1 THEN 'Sim' ELSE 'NÃ£o' END 'Folta Domingo',
	CODTIPO 'CÃ³d Tipo',
	CODSECAO ' CÃ³d SeÃ§Ã£o',
	SECAO 'SeÃ§Ã£o',
	CHEFEDIRETO 'Nome do Chefe Direto'
FROM
(
SELECT
	FUNC.CODCOLIGADA,
	FUNC.CHAPA,
	FUNC.NOME,
	FUNC.DATAADMISSAO,
	PERIODO.DATA,
	PERIODO.DIA,
	PERIODO.TIPO,
	PERIODO.BASE,
	PERIODO.HTRAB,
	PERIODO.EXTRAAUTORIZADO,
	PERIODO.ATRASO,
	PERIODO.FALTA,
	PERIODO.ADICIONAL,
	EXTRAS.HORAS AS EXTRAS,
	PERIODO.REF,
	BANCO.HORAS AS BANCO,
	FUNC.CODTIPO,
	FUNC.CODSECAO,
	FUNC.SECAO,
	FUNC.CHEFEDIRETO,
	CRITICAS.CRITICAINTERJORNADA,
	CRITICAS.CRITICABATSEMPAR,
	CASE WHEN PERIODO.TRABINICIO > (6 * 60) THEN 1 END CRITICAPAUSA,
	CRITICAS.CRITICAMAIS10H,
	PERIODO.FOLGA7DIAS,
	PERIODO.FOLGADOMINGO,
	CASE 
		WHEN PERIODO.BASE > 0 AND PERIODO.BASE > (6*60) AND PERIODO.HTRAB > 0  AND PERIODO.REF = 0 THEN 'Sem Pausa'
		WHEN PERIODO.BASE = 0 AND PERIODO.HTRAB > (6*60) AND PERIODO.HTRAB > 0  AND PERIODO.REF = 0 THEN 'Sem Pausa'
		
		WHEN PERIODO.BASE > 0 AND PERIODO.BASE > (6*60) AND PERIODO.HTRAB > 0  AND PERIODO.REF < 60 THEN 'Menor 60min'
		WHEN PERIODO.BASE = 0 AND PERIODO.HTRAB > (6*60) AND PERIODO.HTRAB > 0  AND PERIODO.REF = 0 THEN 'Menor 60min'
		
		WHEN PERIODO.BASE > 0 AND PERIODO.BASE > (4*60) AND PERIODO.HTRAB > 0  AND PERIODO.REF < 15 THEN 'Menor 15min'
	END CRITICAREF,
	HORARIO.CODHORARIO,
	HORARIO.HORARIO,
	HORARIO.HORINICIO
	
FROM cte_PERIODO AS PERIODO
JOIN cte_FUNC AS FUNC ON
	FUNC.CODCOLIGADA = PERIODO.CODCOLIGADA AND
	FUNC.CHAPA = PERIODO.CHAPA AND
	(FUNC.DTTRANSFERENCIA IS NULL OR FUNC.DTTRANSFERENCIA <= PERIODO.DATA)
LEFT JOIN cte_EXTRAS AS EXTRAS ON
	EXTRAS.CODCOLIGADA = PERIODO.CODCOLIGADA AND
	EXTRAS.CHAPA = PERIODO.CHAPA AND
	EXTRAS.DATA = PERIODO.DATA
LEFT JOIN cte_BANCO AS BANCO ON
	BANCO.CODCOLIGADA = PERIODO.CODCOLIGADA AND
	BANCO.CHAPA = PERIODO.CHAPA AND
	BANCO.DATA = PERIODO.DATA
LEFT JOIN cte_CRITICAS AS CRITICAS ON
	CRITICAS.CODCOLIGADA = PERIODO.CODCOLIGADA AND
	CRITICAS.CHAPA = PERIODO.CHAPA AND
	CRITICAS.DATA = PERIODO.DATA
OUTER APPLY 
	(
	SELECT TOP 1
		cte_HISTHOR.DTMUDANCA,
		cte_HISTHOR.CODHORARIO,
		cte_HISTHOR.TIPO
	FROM cte_HISTHOR
	WHERE
		cte_HISTHOR.CODCOLIGADA = FUNC.CODCOLIGADA AND
		cte_HISTHOR.CHAPA = FUNC.CHAPA
ORDER BY
	cte_HISTHOR.DTMUDANCA DESC
	) HSTHOR
LEFT JOIN cte_HORARIO AS HORARIO ON
	HORARIO.CODCOLIGADA = FUNC.CODCOLIGADA AND
	HORARIO.CODHORARIO = HSTHOR.CODHORARIO AND
	HORARIO.TIPO = HSTHOR.TIPO
) T
WHERE
	(
	@CRITICA <> 'S' OR
	(@CRITICA = 'S' AND 
		(
		EXTRAAUTORIZADO > 0 OR 
		ATRASO > 0 OR 
		FALTA > 0 OR 
		EXTRAS > 0 OR 
		BANCO > 0 OR 
		ADICIONAL > 0 OR
		isnull(CRITICAREF,'') <> '' OR 
	   	isnull(CRITICAINTERJORNADA,0) <> 0 OR 
	   	isnull(CRITICABATSEMPAR,0) <> 0 OR 
	   	isnull(CRITICAPAUSA,0) <> '' OR 
	   	isnull(CRITICAMAIS10H,0) <> 0 OR 
	   	isnull(FOLGA7DIAS,0) <> 0 OR 
   		isnull(FOLGADOMINGO,0) <> 0
		)
	)
	)
ORDER BY
	CODCOLIGADA,
	CHAPA,
	DATA